import { EmptyState, PageHeader } from "@/components/PageChrome";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Database, LockKeyhole, Plus, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type SkillDraft = { name: string; slug: string; domain: string; difficulty: "Beginner" | "Intermediate" | "Advanced"; demand: number; trending: boolean; description: string };
type MappingDraft = { careerId: string; skillId: string; importance: string; minimumProficiency: string; learningOrder: string; requirementType: "required" | "preferred" };
const emptySkill: SkillDraft = { name: "", slug: "", domain: "", difficulty: "Beginner", demand: 3, trending: false, description: "" };
const emptyMapping: MappingDraft = { careerId: "", skillId: "", importance: "3", minimumProficiency: "2", learningOrder: "1", requirementType: "required" };

export default function Admin() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  const [skill, setSkill] = useState<SkillDraft>(emptySkill);
  const [mapping, setMapping] = useState<MappingDraft>(emptyMapping);
  const [skillFormError, setSkillFormError] = useState("");
  const [mappingFormError, setMappingFormError] = useState("");
  const createSkill = trpc.admin.createSkill.useMutation({ onSuccess: () => { utils.admin.overview.invalidate(); setSkill(emptySkill); toast.success("Skill added"); }, onError: error => toast.error(error.message) });
  const saveMapping = trpc.admin.saveMapping.useMutation({ onSuccess: () => { utils.admin.overview.invalidate(); toast.success("Career-skill mapping saved"); }, onError: error => toast.error(error.message) });

  if (user?.role !== "admin") return <div className="mx-auto max-w-3xl"><PageHeader eyebrow="Restricted area" title="Administrator control room." description="Career catalog and user management are available only to authorized administrators." /><EmptyState title="Access not granted" text="This route is protected on both the interface and server procedure layers. Ask a project administrator if your account needs access." action={<span className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><LockKeyhole size={15} /> Administrator access required</span>} /></div>;
  if (overview.isLoading) return <div className="h-96 animate-pulse rounded-[2rem] bg-slate-200" />;
  if (overview.error) return <EmptyState title="The control room is unavailable" text={overview.error.message} />;
  const data = overview.data!;

  return <div className="mx-auto max-w-7xl">
    <PageHeader eyebrow="Administrator control room" title="Maintain the career intelligence layer." description="Changes here shape the curated skill, career and industry-signal catalog used by students. Career suitability analysis remains profile-specific; skill priority is deterministic." />
    <section className="grid gap-4 md:grid-cols-3"><Info icon={<Database size={19} />} label="Catalog skills" value={data.skills.length} text="Categorized capabilities with demand and emerging markers." /><Info icon={<Database size={19} />} label="Career roles" value={data.careers.length} text="Roles and their configured market signals." /><Info icon={<UsersRound size={19} />} label="Registered users" value={data.users.length} text="Visible to administrators only." /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2">
      <form noValidate onSubmit={event => { event.preventDefault(); if (!(skill.name && skill.slug && skill.domain)) { setSkillFormError("Skill name, slug, and domain are required before the catalog can be updated."); return; } setSkillFormError(""); createSkill.mutate(skill); }} className="soft-card rounded-[1.7rem] p-6">
        <p className="eyebrow">Skill management</p><h2 className="display mt-1 text-2xl font-extrabold">Add catalog skill</h2>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 [&_input]:w-full">
          <input aria-invalid={Boolean(skillFormError && !skill.name)} value={skill.name} onChange={event => { setSkill({ ...skill, name: event.target.value }); setSkillFormError(""); }} placeholder="Skill name" />
          <input aria-invalid={Boolean(skillFormError && !skill.slug)} value={skill.slug} onChange={event => { setSkill({ ...skill, slug: event.target.value.toLowerCase().replace(/\s+/g, "-") }); setSkillFormError(""); }} placeholder="slug" />
          <input aria-invalid={Boolean(skillFormError && !skill.domain)} value={skill.domain} onChange={event => { setSkill({ ...skill, domain: event.target.value }); setSkillFormError(""); }} placeholder="Domain" />
          <select value={skill.difficulty} onChange={event => setSkill({ ...skill, difficulty: event.target.value as SkillDraft["difficulty"] })}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select>
          <select value={skill.demand} onChange={event => setSkill({ ...skill, demand: Number(event.target.value) })}>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>Demand {value}/5</option>)}</select>
          <label className="flex items-center gap-2 rounded-xl bg-[#f7f8fa] px-3 text-sm font-semibold"><input type="checkbox" checked={skill.trending} onChange={event => setSkill({ ...skill, trending: event.target.checked })} /> Emerging skill</label>
        </div>
        <textarea className="mt-3 w-full" rows={3} value={skill.description} onChange={event => setSkill({ ...skill, description: event.target.value })} placeholder="Short description (optional)" />
        {skillFormError && <p role="alert" className="mt-3 text-xs font-semibold text-rose-600">{skillFormError}</p>}
        <button disabled={createSkill.isPending} className="button-press mt-4 inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> Add skill</button>
      </form>
      <form noValidate onSubmit={event => { event.preventDefault(); if (!(mapping.careerId && mapping.skillId)) { setMappingFormError("Choose both a career and a skill before saving a requirement mapping."); return; } setMappingFormError(""); saveMapping.mutate({ careerId: Number(mapping.careerId), skillId: Number(mapping.skillId), importance: Number(mapping.importance), minimumProficiency: Number(mapping.minimumProficiency), learningOrder: Number(mapping.learningOrder), requirementType: mapping.requirementType }); }} className="soft-card rounded-[1.7rem] p-6">
        <p className="eyebrow">Requirement mappings</p><h2 className="display mt-1 text-2xl font-extrabold">Map a skill to a career</h2>
        <div className="mt-5 grid gap-3 sm:grid-cols-2">
          <select aria-invalid={Boolean(mappingFormError && !mapping.careerId)} value={mapping.careerId} onChange={event => { setMapping({ ...mapping, careerId: event.target.value }); setMappingFormError(""); }}><option value="">Choose career</option>{data.careers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
          <select aria-invalid={Boolean(mappingFormError && !mapping.skillId)} value={mapping.skillId} onChange={event => { setMapping({ ...mapping, skillId: event.target.value }); setMappingFormError(""); }}><option value="">Choose skill</option>{data.skills.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
          <select value={mapping.requirementType} onChange={event => setMapping({ ...mapping, requirementType: event.target.value as MappingDraft["requirementType"] })}><option value="required">Required</option><option value="preferred">Preferred</option></select>
          <select value={mapping.importance} onChange={event => setMapping({ ...mapping, importance: event.target.value })}>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>Importance {value}/5</option>)}</select>
          <select value={mapping.minimumProficiency} onChange={event => setMapping({ ...mapping, minimumProficiency: event.target.value })}>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>Minimum level {value}/5</option>)}</select>
          <select value={mapping.learningOrder} onChange={event => setMapping({ ...mapping, learningOrder: event.target.value })}>{[1, 2, 3, 4, 5, 6, 7, 8].map(value => <option key={value} value={value}>Learning order {value}</option>)}</select>
        </div>
        {mappingFormError && <p role="alert" className="mt-3 text-xs font-semibold text-rose-600">{mappingFormError}</p>}
        <button disabled={saveMapping.isPending} className="button-press mt-4 inline-flex items-center gap-2 rounded-xl bg-[#dbe9ff] px-4 py-2.5 text-sm font-semibold text-[#28558e]"><Plus size={16} /> Save mapping</button>
        <p className="mt-3 text-xs leading-5 text-slate-500">Existing mapping pairs are updated; new pairs are added. Requirement type, importance, proficiency and order feed the deterministic roadmap.</p>
      </form>
    </section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><CareerManager careers={data.careers} /><TrendManager trends={data.trends} /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <article className="soft-card overflow-hidden rounded-[1.7rem]"><div className="border-b border-slate-200 p-6"><p className="eyebrow">Registered users</p><h2 className="display mt-1 text-2xl font-extrabold">Account visibility</h2></div><div className="max-h-80 overflow-auto">{data.users.map(item => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-slate-100 px-6 py-4"><div><p className="text-sm font-bold">{item.name || "Unnamed student"}</p><p className="text-xs text-slate-500">{item.email || "Email unavailable"}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.role === "admin" ? "bg-[#f6dfe6] text-[#a74f70]" : "bg-[#edf3fe] text-[#3f6ba9]"}`}>{item.role}</span></div>)}</div></article>
      <article className="soft-card rounded-[1.7rem] p-6"><p className="eyebrow">Current mappings</p><h2 className="display mt-1 text-2xl font-extrabold">Requirement coverage</h2><div className="mt-5 max-h-72 space-y-2 overflow-auto">{data.mappings.map(item => <div key={item.id} className="rounded-xl bg-[#f7f8fa] p-3"><p className="text-xs font-bold">{item.careerName} <span className="text-slate-400">→</span> {item.skillName}</p><p className="mt-1 text-[11px] text-slate-500">{item.requirementType} · importance {item.importance}/5 · minimum L{item.minimumProficiency} · order {item.learningOrder}</p></div>)}</div></article>
    </section>
  </div>;
}

function Info({ icon, label, value, text }: { icon: React.ReactNode; label: string; value: number; text: string }) { return <article className="soft-card rounded-2xl p-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#dbe9ff] text-[#28558e]">{icon}</span><p className="eyebrow mt-5">{label}</p><p className="display mt-1 text-3xl font-extrabold">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article>; }

type EditableCareer = { id: number; name: string; slug: string; domain: string; description: string; growthIndicator: string; demand: number };
function CareerManager({ careers }: { careers: EditableCareer[] }) {
  const utils = trpc.useUtils();
  const [editingId, setEditingId] = useState("");
  const [draft, setDraft] = useState({ name: "", slug: "", domain: "", description: "", growthIndicator: "Strong" as "Moderate" | "Strong" | "High", demand: 3 });
  const [formError, setFormError] = useState("");
  const create = trpc.admin.createCareer.useMutation({ onSuccess: () => { utils.admin.overview.invalidate(); setDraft({ name: "", slug: "", domain: "", description: "", growthIndicator: "Strong", demand: 3 }); toast.success("Career role added"); }, onError: error => toast.error(error.message) });
  const update = trpc.admin.updateCareer.useMutation({ onSuccess: () => { utils.admin.overview.invalidate(); toast.success("Career role updated"); }, onError: error => toast.error(error.message) });
  function choose(value: string) { setEditingId(value); const career = careers.find(item => item.id === Number(value)); if (career) setDraft({ name: career.name, slug: career.slug, domain: career.domain, description: career.description, growthIndicator: career.growthIndicator as "Moderate" | "Strong" | "High", demand: career.demand }); else setDraft({ name: "", slug: "", domain: "", description: "", growthIndicator: "Strong", demand: 3 }); }
  return <form noValidate onSubmit={event => { event.preventDefault(); if (!(draft.name && draft.slug && draft.domain && draft.description.trim().length >= 20)) { setFormError("Career name, slug, domain, and a description of at least 20 characters are required."); return; } setFormError(""); if (editingId) update.mutate({ id: Number(editingId), ...draft }); else create.mutate(draft); }} className="soft-card rounded-[1.7rem] p-6"><p className="eyebrow">Career management</p><h2 className="display mt-1 text-2xl font-extrabold">{editingId ? "Edit career role" : "Add career role"}</h2><p className="mt-2 text-sm leading-6 thin-copy">Define a new role or update an existing role before mapping its requirements in the panel above.</p><select className="mt-5 w-full" value={editingId} onChange={event => choose(event.target.value)}><option value="">Add a new career role</option>{careers.map(career => <option key={career.id} value={career.id}>Edit: {career.name}</option>)}</select><div className="mt-3 grid gap-3 sm:grid-cols-2"><input aria-invalid={Boolean(formError && !draft.name)} value={draft.name} onChange={event => { setDraft({ ...draft, name: event.target.value }); setFormError(""); }} placeholder="Career name" /><input aria-invalid={Boolean(formError && !draft.slug)} value={draft.slug} onChange={event => { setDraft({ ...draft, slug: event.target.value.toLowerCase().replace(/\s+/g, "-") }); setFormError(""); }} placeholder="slug" /><input aria-invalid={Boolean(formError && !draft.domain)} value={draft.domain} onChange={event => { setDraft({ ...draft, domain: event.target.value }); setFormError(""); }} placeholder="Domain" /><select value={draft.growthIndicator} onChange={event => setDraft({ ...draft, growthIndicator: event.target.value as "Moderate" | "Strong" | "High" })}><option>Moderate</option><option>Strong</option><option>High</option></select><select value={draft.demand} onChange={event => setDraft({ ...draft, demand: Number(event.target.value) })}>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>Demand {value}/5</option>)}</select></div><textarea aria-invalid={Boolean(formError && draft.description.trim().length < 20)} className="mt-3 w-full" rows={3} value={draft.description} onChange={event => { setDraft({ ...draft, description: event.target.value }); setFormError(""); }} placeholder="Career description (at least 20 characters)" />{formError && <p role="alert" className="mt-3 text-xs font-semibold text-rose-600">{formError}</p>}<button disabled={create.isPending || update.isPending} className="button-press mt-4 inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} /> {editingId ? "Save career changes" : "Add career role"}</button></form>;
}

type Trend = { id: number; title: string; summary: string; relatedDomain: string; impact: string; active: boolean };
function TrendManager({ trends }: { trends: Trend[] }) {
  const utils = trpc.useUtils();
  const [selectedId, setSelectedId] = useState("");
  const [draft, setDraft] = useState<Trend | null>(null);
  const [formError, setFormError] = useState("");
  const update = trpc.admin.updateTrend.useMutation({ onSuccess: () => { utils.admin.overview.invalidate(); toast.success("Industry signal updated"); }, onError: error => toast.error(error.message) });
  function choose(value: string) { const trend = trends.find(item => item.id === Number(value)) ?? null; setSelectedId(value); setDraft(trend ? { ...trend } : null); }
  return <form noValidate onSubmit={event => { event.preventDefault(); if (!draft) { setFormError("Choose an industry signal before saving changes."); return; } if (!(draft.title && draft.relatedDomain && draft.summary.trim().length >= 10)) { setFormError("Signal title, domain, and a summary of at least 10 characters are required."); return; } setFormError(""); update.mutate({ ...draft, impact: draft.impact as "Low" | "Medium" | "High" }); }} className="soft-card rounded-[1.7rem] p-6"><p className="eyebrow">Industry signal management</p><h2 className="display mt-1 text-2xl font-extrabold">Update a curated signal</h2><p className="mt-2 text-sm leading-6 thin-copy">These records are clearly labelled as curated, not real-time job-market data.</p><select aria-invalid={Boolean(formError && !draft)} className="mt-5 w-full" value={selectedId} onChange={event => { choose(event.target.value); setFormError(""); }}><option value="">Choose industry signal</option>{trends.map(trend => <option key={trend.id} value={trend.id}>{trend.title}</option>)}</select>{draft ? <div className="mt-3 space-y-3"><input aria-invalid={Boolean(formError && !draft.title)} value={draft.title} onChange={event => { setDraft({ ...draft, title: event.target.value }); setFormError(""); }} placeholder="Signal title" /><input aria-invalid={Boolean(formError && !draft.relatedDomain)} value={draft.relatedDomain} onChange={event => { setDraft({ ...draft, relatedDomain: event.target.value }); setFormError(""); }} placeholder="Domain" /><select value={draft.impact} onChange={event => setDraft({ ...draft, impact: event.target.value })}><option>Low</option><option>Medium</option><option>High</option></select><label className="flex items-center gap-2 rounded-xl bg-[#f7f8fa] px-3 py-2 text-sm font-semibold"><input type="checkbox" checked={draft.active} onChange={event => setDraft({ ...draft, active: event.target.checked })} /> Active signal</label><textarea aria-invalid={Boolean(formError && draft.summary.trim().length < 10)} className="w-full" rows={3} value={draft.summary} onChange={event => { setDraft({ ...draft, summary: event.target.value }); setFormError(""); }} placeholder="Signal summary" /><button disabled={update.isPending} className="button-press inline-flex items-center gap-2 rounded-xl bg-[#f6dfe6] px-4 py-2.5 text-sm font-semibold text-[#a74f70]">Save signal</button></div> : <p className="mt-4 rounded-xl bg-[#f7f8fa] p-3 text-xs text-slate-500">Select a signal to review and edit its visibility, impact and summary.</p>}{formError && <p role="alert" className="mt-3 text-xs font-semibold text-rose-600">{formError}</p>}</form>;
}
