import { ContentSkeleton, InsightCard, PageHeader, ResponsiveChart, StatePanel } from "@/components/PageChrome";
import { ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { trpc } from "@/lib/trpc";
import { Bar, BarChart, Cell, Pie, PieChart, XAxis, YAxis } from "recharts";
import { Activity, BarChart3, CheckCircle2, Target, Trophy } from "lucide-react";
import { Link } from "wouter";

export default function Analytics() {
  const analytics = trpc.career.analytics.useQuery(undefined, { retry: false });
  if (analytics.isLoading) return <div className="mx-auto max-w-7xl"><ContentSkeleton cards={3} rows={3} /></div>;
  if (analytics.error) return <div className="mx-auto max-w-4xl"><StatePanel kind="error" title="Analytics are unavailable" description={analytics.error.message} /></div>;
  const data = analytics.data!;
  if (!data.roadmap) return <div className="mx-auto max-w-4xl"><PageHeader eyebrow="Student analytics" title="Your evidence becomes useful once you set a goal." description="Analytics are generated from recorded skills and roadmap progress. They do not estimate job-market probability." /><StatePanel title="No target-based analytics yet" description="Choose a target career to view a transparent readiness breakdown, gap distribution and learning progress." action={<Link href="/careers" className="button-press rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white">Choose a target</Link>} /></div>;
  const statusCounts = ["completed", "in_progress", "not_started"].map(status => ({ name: status === "completed" ? "Completed" : status === "in_progress" ? "In progress" : "Not started", value: (data.progress || []).filter((item: any) => item.status === status).length, color: status === "completed" ? "#2d7a53" : status === "in_progress" ? "#4e85ce" : "#cbd5e1" }));
  const gapCounts = ["High", "Medium", "Low"].map(priority => ({ name: priority, value: data.gaps.filter(gap => gap.priority === priority).length, color: priority === "High" ? "#cb6684" : priority === "Medium" ? "#d59a3a" : "#74849a" }));
  const milestones = [{ title: "Profile foundation", done: Boolean(data.profile.profile && data.profile.skills.length), detail: "Profile context and at least one recorded skill" }, { title: "Target selected", done: Boolean(data.roadmap), detail: "A chosen target career with a roadmap" }, { title: "First learning action", done: statusCounts[0].value > 0, detail: "At least one roadmap item marked complete" }];
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Student analytics" title="See what your recorded progress is saying." description="Every visualization is derived from your own skills, configured target requirements and saved roadmap status. Curated demand is not real-time market data." />
    <section className="grid gap-5 xl:grid-cols-3"><InsightCard eyebrow="Readiness" title={`${data.readiness?.score ?? 0}/100`} description="Application-defined: 70% weighted required-skill coverage plus 30% roadmap completion." action={<Target className="text-[#315f9c]" size={22} />}><div className="mt-4 space-y-3 text-xs"><div className="flex justify-between"><span className="text-slate-500">Skill coverage</span><b>{data.readiness?.skillCoverage ?? 0}%</b></div><div className="flex justify-between"><span className="text-slate-500">Roadmap completion</span><b>{data.readiness?.roadmapCompletion ?? 0}%</b></div></div></InsightCard><InsightCard eyebrow="Recorded learning" title={`${statusCounts[0].value} completed`} description="No inferred activity: only items you explicitly marked complete count here." action={<CheckCircle2 className="text-[#2d7a53]" size={22} />}><ResponsiveChart label="Roadmap status distribution" config={{ value: { label: "Items", color: "#4e85ce" } }}><PieChart><Pie data={statusCounts} dataKey="value" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={3}>{statusCounts.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><ChartTooltip content={<ChartTooltipContent hideLabel />} /></PieChart></ResponsiveChart></InsightCard><InsightCard eyebrow="Actual milestones" title="Your journey signals" description="These milestones unlock only when corresponding persisted student actions exist." action={<Trophy className="text-[#b25273]" size={22} />}><div className="mt-3 space-y-2">{milestones.map(item => <div key={item.title} className={`rounded-xl p-3 ${item.done ? "bg-[#e4f3ea]" : "bg-[#f7f8fa]"}`}><p className="text-xs font-bold">{item.done ? "Unlocked" : "In progress"} · {item.title}</p><p className="mt-1 text-[11px] text-slate-500">{item.detail}</p></div>)}</div></InsightCard></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><InsightCard eyebrow="Skill distribution" title="Your recorded proficiency" description="Levels are only the values you selected for skills in your profile." action={<BarChart3 className="text-[#315f9c]" size={22} />}><ResponsiveChart label="Recorded skill proficiency chart" config={{ level: { label: "Proficiency", color: "#4e85ce" } }}><BarChart data={data.skillDistribution.slice(0, 12)} margin={{ left: -14, right: 12 }}><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} interval={0} angle={-32} textAnchor="end" height={52} /><YAxis domain={[0, 5]} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="level" radius={[8, 8, 0, 0]} fill="#4e85ce" /></BarChart></ResponsiveChart></InsightCard><InsightCard eyebrow="Gap priorities" title="Where effort will have the most effect" description="A deterministic distribution of missing required skills for your selected target." action={<Activity className="text-[#b25273]" size={22} />}><ResponsiveChart label="Skill gap priority chart" config={{ value: { label: "Skills", color: "#cb6684" } }}><BarChart data={gapCounts} margin={{ left: -14, right: 12 }}><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="value" radius={[8, 8, 0, 0]}>{gapCounts.map(item => <Cell key={item.name} fill={item.color} />)}</Bar></BarChart></ResponsiveChart></InsightCard></section>
  </div>;
}
