import { ContentSkeleton, InsightCard, PageHeader, ProgressBar, StatePanel } from "@/components/PageChrome";
import { interactiveCard, Reveal } from "@/components/Motion";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Compass, LoaderCircle, Scale, Sparkles, Target } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

type Prediction = { careerId: number; careerName: string; domain: string; score: number; explanation: string };
type SavedAnalysis = { profileSummary: string; predictions: Prediction[]; notice?: string };
function parseAnalysis(value: unknown): SavedAnalysis | null { if (!value || typeof value !== "object") return null; const input = value as Partial<SavedAnalysis>; if (!Array.isArray(input.predictions) || typeof input.profileSummary !== "string") return null; const predictions = input.predictions.filter((item): item is Prediction => Boolean(item && typeof item.careerId === "number" && typeof item.careerName === "string" && typeof item.score === "number" && typeof item.explanation === "string")); return predictions.length ? { profileSummary: input.profileSummary, predictions, notice: input.notice } : null; }

export default function Careers() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const catalog = trpc.career.catalog.useQuery();
  const profile = trpc.profile.get.useQuery(undefined, { retry: false });
  const persistedAnalysis = trpc.career.latestAnalysis.useQuery(undefined, { retry: false });
  const [compareIds, setCompareIds] = useState<number[]>([]);
  const analysis = trpc.career.analyze.useMutation({ onSuccess: () => { utils.career.latestAnalysis.invalidate(); toast.success("Career analysis saved"); }, onError: error => toast.error(error.message) });
  const selectTarget = trpc.career.selectTarget.useMutation({ onSuccess: () => { toast.success("Target career and roadmap created"); setLocation("/roadmap"); }, onError: error => toast.error(error.message) });
  const firstComparison = trpc.career.details.useQuery({ careerId: compareIds[0] ?? 1 }, { enabled: Boolean(compareIds[0]) });
  const secondComparison = trpc.career.details.useQuery({ careerId: compareIds[1] ?? 1 }, { enabled: Boolean(compareIds[1]) });
  const saved = parseAnalysis(persistedAnalysis.data?.results);
  const currentAnalysis = analysis.data ? { profileSummary: analysis.data.profileSummary, predictions: analysis.data.predictions, notice: analysis.data.notice } : saved;
  const scores = useMemo(() => new Map(currentAnalysis?.predictions.map(item => [item.careerId, item.score]) ?? []), [currentAnalysis]);
  if (catalog.isLoading || profile.isLoading || persistedAnalysis.isLoading) return <div className="mx-auto max-w-7xl"><ContentSkeleton cards={3} rows={4} /></div>;
  if (profile.error) return <div className="mx-auto max-w-4xl"><StatePanel kind="error" title="Sign in to explore careers" description={profile.error.message} /></div>;
  const ready = Boolean(profile.data?.skills.length || profile.data?.profile?.interests.length);
  const selected = catalog.data?.careers.filter(career => compareIds.includes(career.id)) ?? [];
  const comparisonSnapshots = [firstComparison.data, secondComparison.data].filter(Boolean);
  function toggleCompare(careerId: number) { setCompareIds(current => current.includes(careerId) ? current.filter(id => id !== careerId) : current.length === 2 ? [current[1], careerId] : [...current, careerId]); }

  return <div className="mx-auto max-w-7xl">
    <PageHeader eyebrow="Career intelligence" title="Explore direction with evidence." description="Model-derived suitability estimates are shown alongside deterministic requirement and gap information. Choose any target career, regardless of the ranking." action={<button disabled={!ready || analysis.isPending} onClick={() => analysis.mutate()} className="button-press inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{analysis.isPending ? <LoaderCircle size={16} className="animate-spin" /> : <Sparkles size={16} />}{analysis.isPending ? "Assessing profile…" : "Analyze my profile"}</button>} />
    {!ready && <section className="mb-5"><StatePanel title="Give your analysis context first." description="Add at least one skill or interest. You can keep optional profile evidence for later, but the analysis needs a starting signal." action={<button onClick={() => setLocation("/profile")} className="button-press rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white">Complete profile</button>} /></section>}
    {currentAnalysis ? <Reveal><section className="mb-6 rounded-[1.8rem] bg-[#17233c] p-5 text-white sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="eyebrow text-slate-400">Saved LLM career assessment</p><h2 className="display mt-2 text-3xl font-extrabold">Your strongest current alignments</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{currentAnalysis.profileSummary}</p></div><span className="max-w-xs rounded-2xl bg-white/10 px-3 py-2 text-xs leading-5 text-[#d3e4ff]">Model-derived suitability is an alignment estimate, not a guarantee of career outcomes.</span></div><div className="mt-6 grid gap-3 lg:grid-cols-3">{currentAnalysis.predictions.map((item, index) => <article key={item.careerId} className={`rounded-2xl p-4 ${index === 0 ? "bg-[#2e4f82]" : "bg-white/10"}`}><div className="flex items-center justify-between"><span className="eyebrow text-slate-300">Match {index + 1}</span><span className="display text-3xl font-extrabold">{item.score}%</span></div><h3 className="display mt-5 text-xl font-extrabold">{item.careerName}</h3><p className="mt-1 text-xs text-[#b9d4ff]">{item.domain}</p><p className="mt-3 text-xs leading-5 text-slate-200">{item.explanation}</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={() => selectTarget.mutate({ careerId: item.careerId })} className="text-xs font-bold text-white underline decoration-white/40 underline-offset-4">Make target</button><button onClick={() => toggleCompare(item.careerId)} className="text-xs font-bold text-[#cfe2ff] underline decoration-[#cfe2ff]/40 underline-offset-4">{compareIds.includes(item.careerId) ? "Remove comparison" : "Compare"}</button></div></article>)}</div></section></Reveal> : ready && <section className="mb-6"><StatePanel title="Your career analysis has not been generated yet." description="Use the profile-aware assessment to create a saved, model-derived set of three to five career matches." action={<button onClick={() => analysis.mutate()} className="button-press inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white"><Sparkles size={16} /> Analyze my career</button>} /></section>}
    <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
      <InsightCard eyebrow="Career comparison" title={selected.length === 2 ? `${selected[0]?.name} vs ${selected[1]?.name}` : "Compare two career paths"} description={selected.length === 2 ? "Suitability is model-derived when saved analysis includes a career; requirements, gaps, demand and growth are rule or catalog data." : "Select up to two careers below. Selecting a third replaces the oldest choice."} action={<Scale className="text-[#315f9c]" size={22} />}>
        {selected.length === 2 && comparisonSnapshots.length === 2 ? <div className="grid gap-3 md:grid-cols-2">{comparisonSnapshots.map(snapshot => snapshot && <article key={snapshot.career.id} className="rounded-2xl bg-[#f8f9fb] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">{snapshot.career.name}</p><p className="mt-1 text-xs text-slate-500">{snapshot.career.domain}</p></div><span className="rounded-full bg-[#e5efff] px-2.5 py-1 text-[10px] font-bold text-[#315f9c]">{scores.has(snapshot.career.id) ? `${scores.get(snapshot.career.id)}% model fit` : "No saved model score"}</span></div><dl className="mt-5 space-y-2 text-xs"><div className="flex justify-between gap-4"><dt className="text-slate-500">Curated demand</dt><dd className="font-bold">{snapshot.career.demand}/5</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Growth signal</dt><dd className="font-bold">{snapshot.career.growthIndicator}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Required gaps</dt><dd className="font-bold">{snapshot.gaps.length}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">High-priority gaps</dt><dd className="font-bold">{snapshot.gaps.filter(gap => gap.priority === "High").length}</dd></div></dl><button onClick={() => selectTarget.mutate({ careerId: snapshot.career.id })} className="mt-5 inline-flex items-center gap-1.5 text-xs font-bold text-[#315f9c]">Make target <ArrowRight size={14} /></button></article>)}</div> : <StatePanel title="Choose two careers to compare." description="The comparison brings together catalog demand and growth signals with your own rule-based skill gaps. It never invents a model score." />}
      </InsightCard>
      <InsightCard eyebrow="Target career mode" title="Pick the path you want to pursue." description="Selecting a target becomes the basis for your deterministic skill-gap analysis, dependency-aware roadmap, and readiness indicator." action={<Target className="text-[#b25273]" size={22} />}><div className="rounded-2xl bg-[#f6e0e7] p-4 text-sm leading-6 text-[#743a53]">Current skills → target requirements → deterministic gap priorities → prerequisite-aware roadmap. This sequence is application logic, not a model claim.</div></InsightCard>
    </section>
    <section className="mt-5"><div className="mb-4 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf3fe] text-[#315f9c]"><Compass size={18} /></span><div><p className="eyebrow">Career catalog</p><p className="text-sm text-slate-600">Select a target, or add two roles to the comparison view.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{catalog.data?.careers.map(career => <article key={career.id} className={`soft-card flex flex-col rounded-[1.5rem] p-5 ${interactiveCard}`}><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-[#edf3fe] px-2.5 py-1 text-[10px] font-bold text-[#3f6ba9]">{career.domain}</span><h2 className="display mt-4 text-2xl font-extrabold">{career.name}</h2></div><button onClick={() => toggleCompare(career.id)} aria-pressed={compareIds.includes(career.id)} className={`grid h-9 w-9 place-items-center rounded-xl ${compareIds.includes(career.id) ? "bg-[#17233c] text-white" : "bg-[#f7f8fa] text-slate-500"}`} aria-label={`Toggle ${career.name} in comparison`}><Scale size={16} /></button></div><p className="mt-3 flex-1 text-sm leading-6 thin-copy">{career.description}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-[#f8f9fb] p-3"><p className="text-slate-500">Demand</p><p className="mt-1 font-bold">{career.demand}/5</p></div><div className="rounded-xl bg-[#f8f9fb] p-3"><p className="text-slate-500">Growth</p><p className="mt-1 font-bold">{career.growthIndicator}</p></div></div>{scores.has(career.id) && <div className="mt-3"><div className="mb-1 flex justify-between text-[11px] font-bold text-slate-600"><span>Model-derived alignment</span><span>{scores.get(career.id)}%</span></div><ProgressBar value={scores.get(career.id) ?? 0} tone="blue" /></div>}<button disabled={selectTarget.isPending} onClick={() => selectTarget.mutate({ careerId: career.id })} className="button-press mt-5 inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-800">Set as target <ArrowRight size={15} /></button></article>)}</div></section>
  </div>;
}
