import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { ArrowRight, BarChart3, CheckCircle2, Compass, Sparkles } from "lucide-react";
import { Link } from "wouter";

export default function Home() {
  const { isAuthenticated } = useAuth();
  return <div className="relative min-h-screen overflow-hidden bg-[#eef1f4] page-grid">
    <div className="shape -right-32 top-16 h-72 w-72 bg-[#cfe4ff]" /><div className="shape -left-20 bottom-2 h-64 w-64 bg-[#f4d5df]" />
    <header className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#17233c] text-white"><Sparkles size={18} /></span><span className="display text-xl font-extrabold">CareerCompass</span></Link><div className="flex items-center gap-4"><Link href="/dashboard" className="hidden text-sm font-semibold text-slate-600 sm:block">My workspace</Link><button onClick={() => isAuthenticated ? window.location.assign("/dashboard") : startLogin()} className="button-press rounded-xl bg-[#17233c] px-4 py-2.5 text-sm font-semibold text-white">{isAuthenticated ? "Open workspace" : "Sign in"}</button></div></header>
    <main className="relative z-10 mx-auto max-w-6xl px-6 pb-16 pt-16 lg:pt-24"><section className="grid items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><div className="float-in"><p className="eyebrow mb-5">Career intelligence, made usable</p><h1 className="display max-w-3xl text-5xl font-extrabold leading-[.98] sm:text-6xl lg:text-7xl">Find a path that <span className="text-[#3569ac]">fits your momentum.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 thin-copy">CareerCompass pairs a considered AI assessment with transparent, rule-based skill-gap analysis—so students can turn today’s capabilities into a deliberate next step.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={() => isAuthenticated ? window.location.assign("/dashboard") : startLogin()} className="button-press flex items-center justify-center gap-2 rounded-xl bg-[#17233c] px-5 py-3.5 font-semibold text-white">Build my profile <ArrowRight size={17} /></button><a href="#method" className="button-press rounded-xl border border-slate-300 bg-white px-5 py-3.5 text-center font-semibold text-slate-700">See how it works</a></div><p className="mt-4 text-xs text-slate-500">Suitability scores describe profile alignment; they do not guarantee career outcomes.</p></div>
      <div className="soft-card float-in relative rounded-[2.2rem] p-5 [animation-delay:80ms]"><div className="rounded-[1.6rem] bg-[#17233c] p-6 text-white"><p className="eyebrow text-slate-400">Career snapshot</p><div className="mt-7 flex items-end justify-between"><div><p className="text-sm text-slate-300">Profile readiness</p><p className="display mt-1 text-5xl font-extrabold">72<span className="text-2xl">/100</span></p></div><span className="rounded-full bg-[#264675] px-3 py-1.5 text-xs">Illustrative layout</span></div><div className="mt-8 h-2 overflow-hidden rounded-full bg-slate-600"><div className="h-full w-[72%] rounded-full bg-[#b7d2ff]" /></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#e1edff] p-4"><Compass className="text-[#3569ac]" size={20}/><p className="mt-4 text-sm font-semibold">Discover direction</p><p className="mt-1 text-xs leading-5 text-slate-500">Ranked career options with clear rationale.</p></div><div className="rounded-2xl bg-[#f6e0e7] p-4"><BarChart3 className="text-[#b45372]" size={20}/><p className="mt-4 text-sm font-semibold">Measure progress</p><p className="mt-1 text-xs leading-5 text-slate-500">Track roadmap completion over time.</p></div></div></div></section>
    <section id="method" className="mt-28 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 sm:grid-cols-3"><Method icon={<Compass size={19}/>} number="01" title="Describe your present" text="Capture education, skills, interests, projects, certifications, and experience."/><Method icon={<Sparkles size={19}/>} number="02" title="Assess alignment" text="Receive a ranked, natural-language assessment against the curated career catalog."/><Method icon={<CheckCircle2 size={19}/>} number="03" title="Move deliberately" text="Choose any target career and progress through a transparent skill roadmap."/></section></main>
  </div>;
}
function Method({ icon, number, title, text }: { icon: React.ReactNode; number: string; title: string; text: string }) { return <article className="bg-[#f9fafb] p-7"><div className="flex items-center justify-between text-[#3569ac]">{icon}<span className="eyebrow">{number}</span></div><h2 className="display mt-8 text-xl font-extrabold">{title}</h2><p className="mt-3 text-sm leading-6 thin-copy">{text}</p></article>; }
