import { ContentSkeleton, InsightCard, PageHeader, ProgressBar, StatePanel } from "@/components/PageChrome";
import { Reveal } from "@/components/Motion";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BookOpenCheck, CheckCircle2, Circle, CircleDot, LockKeyhole, Rocket, Target } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

const labels: Record<string, string> = { not_started: "Not started", in_progress: "In progress", completed: "Completed" };

export default function Journey() {
  const utils = trpc.useUtils();
  const journey = trpc.career.journey.useQuery(undefined, { retry: false });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const update = trpc.career.updateProgress.useMutation({ onSuccess: () => { utils.career.journey.invalidate(); utils.career.roadmap.invalidate(); utils.career.analytics.invalidate(); toast.success("Learning progress updated"); }, onError: error => toast.error(error.message) });
  if (journey.isLoading) return <div className="mx-auto max-w-7xl"><ContentSkeleton cards={3} rows={5} /></div>;
  if (journey.error) return <div className="mx-auto max-w-4xl"><StatePanel kind="error" title="Your career journey is unavailable" description={journey.error.message} /></div>;
  const data = journey.data;
  if (!data) return <div className="mx-auto max-w-4xl"><PageHeader eyebrow="Career journey" title="A target turns learning into a route." description="Choose any target career to see a dependency-aware learning path built from configured prerequisite relationships." /><StatePanel title="No active career journey" description="Target career mode creates a roadmap and unlocks this visual journey." action={<Link href="/careers" className="button-press inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white">Choose a target <ArrowRight size={16} /></Link>} /></div>;
  const selected = (data.roadmap?.items || []).find((item: any) => item.id === selectedId) ?? (data.roadmap?.items || []).find((item: any) => item.status !== "completed") ?? data.roadmap?.items[0];
  const skillById = new Map((data.graph.skills || []).map((skill: any) => [skill.id, skill]));
  const selectedPrerequisites = selected ? (data.graph.edges || []).filter((edge: any) => edge.skillId === selected.skillId).map((edge: any) => skillById.get(edge.prerequisiteSkillId)).filter(Boolean) : [];
  const completed = (data.roadmap?.items || []).filter((item: any) => item.status === "completed").length ?? 0;
  const total = data.roadmap?.items?.length ?? 0;
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Interactive career journey" title={`Your route to ${data.career.name}.`} description="Nodes follow your prerequisite graph. Completed work is activated; the first incomplete item is highlighted as the next recommended focus." action={<div className="soft-card min-w-52 rounded-2xl p-3"><div className="mb-2 flex justify-between text-xs font-bold text-slate-600"><span>Journey completion</span><span>{data.readiness.roadmapCompletion}%</span></div><ProgressBar value={data.readiness.roadmapCompletion} tone="blue" /></div>} />
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><InsightCard eyebrow="Learning route" title="From your profile to target career" description="This visual sequence uses stored roadmap statuses and configured skill prerequisites—not generated completion data." action={<Rocket className="text-[#315f9c]" size={22} />}><div className="relative mt-1 space-y-0 before:absolute before:bottom-8 before:left-[19px] before:top-8 before:w-px before:bg-[#cdd8e7]">{(data.roadmap?.items || []).map((item: any, index: number) => { const isSelected = selected?.id === item.id; const isNext = item.status !== "completed" && (data.roadmap?.items || []).find((entry: any) => entry.status !== "completed")?.id === item.id; const Icon = item.status === "completed" ? CheckCircle2 : item.status === "in_progress" ? CircleDot : Circle; return <button key={item.id} onClick={() => setSelectedId(item.id)} className={`relative z-10 flex w-full items-center gap-4 rounded-2xl p-3 text-left transition ${isSelected ? "bg-[#edf3fe]" : "hover:bg-[#f8f9fb]"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full border-4 border-white shadow-sm ${item.status === "completed" ? "bg-[#2d7a53] text-white" : item.status === "in_progress" ? "bg-[#315f9c] text-white" : "bg-white text-slate-400"}`}><Icon size={17} /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="text-sm font-bold">{item.skillName}</span>{isNext && <span className="rounded-full bg-[#f6e0e7] px-2 py-0.5 text-[10px] font-bold text-[#a74f70]">Next focus</span>}</span><span className="mt-1 block text-xs leading-5 text-slate-500">Stage {index + 1} · {labels[item.status] ?? item.status}</span></span><ArrowRight size={16} className="text-slate-400" /></button>; })}<div className="relative z-10 flex items-center gap-4 rounded-2xl p-3"><span className="grid h-10 w-10 place-items-center rounded-full border-4 border-white bg-[#17233c] text-white shadow-sm"><Target size={17} /></span><span><span className="text-sm font-bold">{data.career.name}</span><span className="mt-1 block text-xs text-slate-500">Target career · readiness {data.readiness.score}/100</span></span></div></div></InsightCard>
      <InsightCard eyebrow="Node details" title={selected ? `Why ${selected.skillName} matters` : "Choose a skill node"} description={selected?.description || "Select a node in your journey to inspect the stored requirement and progress context."} action={<BookOpenCheck className="text-[#b25273]" size={22} />}>{selected ? <><div className="grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-[#f8f9fb] p-3"><p className="text-slate-500">Learning status</p><p className="mt-1 font-bold">{labels[selected.status] ?? selected.status}</p></div><div className="rounded-xl bg-[#f8f9fb] p-3"><p className="text-slate-500">Prerequisites</p><p className="mt-1 font-bold">{selectedPrerequisites.length}</p></div></div><div className="mt-4"><p className="eyebrow">Prerequisite skills</p>{selectedPrerequisites.length ? <div className="mt-2 flex flex-wrap gap-2">{selectedPrerequisites.map((skill: any) => skill && <span key={skill.id} className="rounded-full bg-[#edf3fe] px-3 py-1.5 text-xs font-bold text-[#315f9c]">{skill.name}</span>)}</div> : <p className="mt-2 text-sm text-slate-500">No configured prerequisite is required before this node.</p>}</div><div className="mt-5 flex flex-wrap gap-2">{(["not_started", "in_progress", "completed"] as const).map(status => <button key={status} disabled={status === selected.status || update.isPending} onClick={() => update.mutate({ roadmapItemId: selected.id, status })} className={`button-press rounded-xl px-3 py-2 text-xs font-bold ${status === selected.status ? "bg-[#17233c] text-white" : "bg-[#f7f8fa] text-slate-600 hover:bg-[#edf3fe]"}`}>{labels[status] ?? status}</button>)}</div><p className="mt-5 rounded-xl bg-[#f6f8fb] p-3 text-xs leading-5 text-slate-600">Recommended resources are intentionally not shown until they are curated by an administrator. CareerCompass does not fabricate learning links.</p></> : <StatePanel title="Pick a learning node" description="The active node will show its progress state, rationale and prerequisite skills here." />}</InsightCard></section>
    <Reveal delay={0.06}><section className="mt-5 grid gap-4 sm:grid-cols-3"><InsightCard eyebrow="You are here" title={`${completed} of ${total} nodes complete`} description="Recorded roadmap progress only." action={<CheckCircle2 className="text-[#2d7a53]" size={20} />}><p className="display text-4xl font-extrabold">{data.readiness.roadmapCompletion}%</p></InsightCard><InsightCard eyebrow="Rule-based skill coverage" title={`${data.readiness.skillCoverage}%`} description="Weighted required-skill coverage for the selected target." action={<CircleDot className="text-[#315f9c]" size={20} />}><ProgressBar value={data.readiness.skillCoverage} tone="blue" /></InsightCard><InsightCard eyebrow="Application-defined readiness" title={`${data.readiness.score}/100`} description="70% weighted skill coverage plus 30% roadmap completion; not an employment probability." action={<LockKeyhole className="text-[#a74f70]" size={20} />}><p className="text-sm leading-6 thin-copy">Use this to understand progress, not to predict an outcome.</p></InsightCard></section></Reveal>
  </div>;
}
