import { ContentSkeleton, InsightCard, PageHeader, StatePanel } from "@/components/PageChrome";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, CircleAlert, Gauge, Target } from "lucide-react";
import { Link } from "wouter";

const priorityStyles = { High: "bg-[#ffe3e6] text-[#b43d55]", Medium: "bg-[#fff0d4] text-[#956112]", Low: "bg-[#e8eef7] text-[#536477]" };
function level(level: number) { return level === 0 ? "Not recorded" : ["", "Beginner", "Basic", "Intermediate", "Advanced", "Expert"][level] ?? `Level ${level}`; }

export default function SkillGap() {
  const profile = trpc.profile.get.useQuery(undefined, { retry: false });
  const roadmap = trpc.career.roadmap.useQuery(undefined, { retry: false });
  if (profile.isLoading || roadmap.isLoading) return <div className="mx-auto max-w-7xl"><ContentSkeleton cards={3} rows={5} /></div>;
  if (profile.error || roadmap.error) return <div className="mx-auto max-w-4xl"><StatePanel kind="error" title="Skill-gap analysis is unavailable" description={profile.error?.message ?? roadmap.error?.message ?? "Please try again."} /></div>;
  const data = roadmap.data;
  if (!data) return <div className="mx-auto max-w-4xl"><PageHeader eyebrow="Deterministic skill-gap analysis" title="Choose a target to identify the right gaps." description="CareerCompass compares recorded proficiency with the configured requirements of a specific target career." /><StatePanel title="No target career selected" description="Target career mode creates a transparent skill-gap analysis and learning plan." action={<Link href="/careers" className="button-press inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white">Choose target career <ArrowRight size={16} /></Link>} /></div>;
  const studentSkills = (profile.data?.skills ?? []).filter((s): s is NonNullable<typeof s> => Boolean(s));
  const gapIds = new Set(data.gaps.map(gap => gap.skillId));
  const matched = data.requirements.filter(requirement => requirement.requirementType === "required" && !gapIds.has(requirement.skillId));
  const statusBySkill = new Map<number, string>((data.roadmap?.items || []).map((item: any) => [item.skillId, String(item.status)]));
  const groups = (["High", "Medium", "Low"] as const).map(priority => ({ priority, gaps: data.gaps.filter(gap => gap.priority === priority) }));
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Deterministic skill-gap analysis" title={`Your gap to ${data.career.name}.`} description="Missing skills are calculated from your recorded proficiency, required level, configured role importance, curated demand and emerging-skill markers. This is rule-based application logic—not an LLM result." action={<Link href="/journey" className="button-press inline-flex items-center gap-2 rounded-xl bg-[#17233c] px-4 py-3 text-sm font-semibold text-white">Open career journey <ArrowRight size={16} /></Link>} />
    <section className="grid gap-4 sm:grid-cols-3"><InsightCard eyebrow="Current skills" title={`${studentSkills.length} recorded`} description="Skills and proficiency levels you added to your profile." action={<Gauge className="text-[#315f9c]" size={21} />}><div className="mt-3 flex flex-wrap gap-2">{studentSkills.slice(0, 8).map(skill => <span key={skill.skillId} className="rounded-full bg-[#edf3fe] px-3 py-1.5 text-xs font-bold text-[#315f9c]">{skill.name} · L{skill.proficiency}</span>)}{!studentSkills.length && <p className="text-sm text-slate-500">No profile skills recorded.</p>}</div></InsightCard><InsightCard eyebrow="Matched required skills" title={`${matched.length} aligned`} description="Required skills whose recorded level already meets the target." action={<CheckCircle2 className="text-[#2d7a53]" size={21} />}><p className="display text-4xl font-extrabold text-[#2d7a53]">{matched.length}</p></InsightCard><InsightCard eyebrow="Missing required skills" title={`${data.gaps.length} to develop`} description="Only gaps in configured required skills appear in the priority groups below." action={<CircleAlert className="text-[#b25273]" size={21} />}><p className="display text-4xl font-extrabold text-[#b25273]">{data.gaps.length}</p></InsightCard></section>
    {matched.length > 0 && <section className="mt-5"><InsightCard eyebrow="Matched skills" title="Requirements you already meet" description="These configured required skills are separated from gaps because your recorded proficiency meets or exceeds the target level." action={<CheckCircle2 className="text-[#2d7a53]" size={22} />}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{matched.map(requirement => { const current = studentSkills.find(skill => skill.skillId === requirement.skillId)?.proficiency ?? 0; return <article key={requirement.skillId} className="rounded-2xl bg-[#e8f4ec] p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-bold">{requirement.name}</h3><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-[#2d7a53]">Matched</span></div><p className="mt-3 text-xs text-[#4a6758]">Current {level(current)} · required {level(requirement.minimumProficiency)}</p></article>; })}</div></InsightCard></section>}
    {data.gaps.length ? <section className="mt-5 space-y-5">{groups.map(group => group.gaps.length ? <InsightCard key={group.priority} eyebrow={`${group.priority} priority`} title={`${group.gaps.length} ${group.priority.toLowerCase()}-priority skill${group.gaps.length === 1 ? "" : "s"}`} description={group.priority === "High" ? "These have the strongest configured combination of requirement importance, demand, proficiency deficit, and emerging-skill marker." : "Priority reflects the transparent configuration and your current profile."} action={<span className={`rounded-full px-3 py-1.5 text-xs font-bold ${priorityStyles[group.priority]}`}>{group.priority}</span>}><div className="grid gap-3 lg:grid-cols-2">{group.gaps.map(gap => <article key={gap.skillId} className="rounded-2xl bg-[#f8f9fb] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold">{gap.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{gap.explanation}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${priorityStyles[gap.priority]}`}>{gap.priority}</span></div><dl className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><div className="rounded-xl bg-white p-2.5"><dt className="text-slate-500">Current</dt><dd className="mt-1 font-bold">{level(gap.currentLevel)}</dd></div><div className="rounded-xl bg-white p-2.5"><dt className="text-slate-500">Required</dt><dd className="mt-1 font-bold">{level(gap.requiredLevel)}</dd></div><div className="rounded-xl bg-white p-2.5"><dt className="text-slate-500">Gap</dt><dd className="mt-1 font-bold">{gap.requiredLevel - gap.currentLevel} level{gap.requiredLevel - gap.currentLevel === 1 ? "" : "s"}</dd></div><div className="rounded-xl bg-white p-2.5"><dt className="text-slate-500">Demand</dt><dd className="mt-1 font-bold">{gap.demand}/5</dd></div></dl><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs font-semibold text-slate-600">Learning status: {statusBySkill.get(gap.skillId)?.replace("_", " ") ?? "not started"}</span><Link href="/journey" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#315f9c]">Learn <ArrowRight size={14} /></Link></div></article>)}</div></InsightCard> : null)}</section> : <section className="mt-5"><StatePanel kind="success" title="No required skill gaps are currently identified." description="Your recorded proficiency meets the configured required skills for this target. Keep your profile up to date as you build new evidence." /></section>}
  </div>;
}
