import { ContentSkeleton, InsightCard, PageHeader, ResponsiveChart, StatePanel } from "@/components/PageChrome";
import { ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { trpc } from "@/lib/trpc";
import { Bar, BarChart, Cell, XAxis, YAxis } from "recharts";
import { Flame, Radar, TrendingUp } from "lucide-react";

export default function Trends() {
  const catalog = trpc.career.catalog.useQuery();
  if (catalog.isLoading) return <div className="mx-auto max-w-7xl"><ContentSkeleton cards={3} rows={3} /></div>;
  if (catalog.error) return <div className="mx-auto max-w-4xl"><StatePanel kind="error" title="Industry signals are unavailable" description={catalog.error.message} /></div>;
  const skills = catalog.data?.skills.filter(skill => skill.trending) ?? [];
  const inDemandSkills = [...(catalog.data?.skills ?? [])].sort((a, b) => b.demand - a.demand || a.name.localeCompare(b.name)).slice(0, 9).map(skill => ({ name: skill.name, demand: skill.demand, trending: skill.trending }));
  const inDemandCareers = [...(catalog.data?.careers ?? [])].sort((a, b) => b.demand - a.demand || a.name.localeCompare(b.name)).slice(0, 7).map(career => ({ name: career.name, demand: career.demand, growth: career.growthIndicator }));
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Curated industry intelligence" title="Understand the signals behind the catalog." description="These administrator-maintained indicators inform gap prioritization and career context. They are not claims of real-time job-market data." />
    <section className="grid gap-4 lg:grid-cols-3">{catalog.data?.trends.map(trend => <InsightCard key={trend.id} eyebrow={trend.relatedDomain} title={trend.title} description={trend.summary} action={<span className="rounded-full bg-[#edf3fe] px-2.5 py-1 text-[10px] font-bold text-[#3f6ba9]">{trend.impact} impact</span>}><div className="flex items-center gap-2 text-xs font-bold text-[#b25273]"><Radar size={15} /> Curated and administrator-updatable</div></InsightCard>)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><InsightCard eyebrow="Skill demand" title="Highest demand markers in the catalog" description="Demand is a curated scale from 1 to 5. It helps rank deterministic skill gaps; it is not a live vacancy count." action={<TrendingUp className="text-[#315f9c]" size={22} />}><ResponsiveChart label="Curated skill demand chart" config={{ demand: { label: "Demand", color: "#4e85ce" } }}><BarChart data={inDemandSkills} margin={{ left: -14, right: 12 }}><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} interval={0} angle={-32} textAnchor="end" height={58} /><YAxis domain={[0, 5]} tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="demand" radius={[8, 8, 0, 0]}>{inDemandSkills.map(item => <Cell key={item.name} fill={item.trending ? "#cb6684" : "#4e85ce"} />)}</Bar></BarChart></ResponsiveChart><p className="mt-3 text-xs text-slate-500">Pink bars have an emerging-skill marker in the curated catalog.</p></InsightCard><InsightCard eyebrow="Career demand" title="High-demand career paths" description="This display compares administrator-configured career demand and growth signals." action={<Flame className="text-[#b25273]" size={22} />}><ResponsiveChart label="Curated career demand chart" config={{ demand: { label: "Demand", color: "#cb6684" } }}><BarChart data={inDemandCareers} layout="vertical" margin={{ left: 12, right: 12 }}><XAxis type="number" domain={[0, 5]} hide /><YAxis dataKey="name" type="category" width={130} tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="demand" radius={[0, 8, 8, 0]} fill="#cb6684" /></BarChart></ResponsiveChart></InsightCard></section>
    <section className="mt-5"><InsightCard eyebrow="Emerging-skill markers" title="Capabilities the catalog flags for additional attention" description="The rule-based gap engine adds the emerging marker to its priority score when a required skill is also trending." action={<Flame className="text-[#986112]" size={22} />}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{skills.map(skill => <article key={skill.id} className="rounded-2xl bg-[#f8f9fb] p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold">{skill.name}</span><span className="rounded-full bg-[#fff0d4] px-2 py-1 text-[10px] font-bold text-[#986112]">Emerging</span></div><p className="mt-2 text-xs text-slate-500">{skill.domain} · {skill.difficulty}</p><div className="mt-4 flex items-center justify-between"><span className="eyebrow">Curated demand</span><span className="text-xs font-bold">{skill.demand}/5</span></div></article>)}{!skills.length && <StatePanel title="No emerging skills are currently flagged" description="An administrator can update trend markers in the control room." />}</div></InsightCard></section>
  </div>;
}
